# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vod_api.proto',
  package='VODService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rvod_api.proto\x12\nVODService\"C\n\x12HealthCheckMessage\x12-\n\trtsp_urls\x18\x01 \x03(\x0b\x32\x1a.VODService.RtspUrlMessage\"\"\n\x0eRtspUrlMessage\x12\x10\n\x08rtsp_url\x18\x01 \x01(\t\"B\n\x13RTSPFeedHealthCheck\x12\x13\n\x0bstatus_flag\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\"l\n\x11HealthCheckResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12.\n\x05\x66\x65\x65\x64s\x18\x03 \x03(\x0b\x32\x1f.VODService.RTSPFeedHealthCheck\"8\n\x0fVODStartMessage\x12\x13\n\x0bstream_name\x18\x01 \x01(\t\x12\x10\n\x08rtsp_url\x18\x02 \x01(\t\"\"\n\x0eVODStopMessage\x12\x10\n\x08rtsp_url\x18\x01 \x01(\t\";\n\x10VODStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\"\'\n\x10VODStatusMessage\x12\x13\n\x0bstream_name\x18\x01 \x01(\t\"h\n\x11VODStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\x12\x16\n\x0estream_running\x18\x03 \x01(\x08\x12\x12\n\nstream_log\x18\x04 \x01(\t\":\n\x0fVODStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t*8\n\x05\x44Type\x12\t\n\x05UINT8\x10\x00\x12\n\n\x06UINT16\x10\x01\x12\x0b\n\x07\x46LOAT32\x10\x02\x12\x0b\n\x07\x46LOAT64\x10\x03\x32\xbc\x02\n\nVODService\x12G\n\x08StartVOD\x12\x1b.VODService.VODStartMessage\x1a\x1c.VODService.VODStartResponse\"\x00\x12\x44\n\x07StopVOD\x12\x1a.VODService.VODStopMessage\x1a\x1b.VODService.VODStopResponse\"\x00\x12O\n\x0e\x43heckVODStatus\x12\x1c.VODService.VODStatusMessage\x1a\x1d.VODService.VODStatusResponse\"\x00\x12N\n\x0bHealthCheck\x12\x1e.VODService.HealthCheckMessage\x1a\x1d.VODService.HealthCheckResult\"\x00\x62\x06proto3'
)

_DTYPE = _descriptor.EnumDescriptor(
  name='DType',
  full_name='VODService.DType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UINT8', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT16', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOAT32', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOAT64', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=674,
  serialized_end=730,
)
_sym_db.RegisterEnumDescriptor(_DTYPE)

DType = enum_type_wrapper.EnumTypeWrapper(_DTYPE)
UINT8 = 0
UINT16 = 1
FLOAT32 = 2
FLOAT64 = 3



_HEALTHCHECKMESSAGE = _descriptor.Descriptor(
  name='HealthCheckMessage',
  full_name='VODService.HealthCheckMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtsp_urls', full_name='VODService.HealthCheckMessage.rtsp_urls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=96,
)


_RTSPURLMESSAGE = _descriptor.Descriptor(
  name='RtspUrlMessage',
  full_name='VODService.RtspUrlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtsp_url', full_name='VODService.RtspUrlMessage.rtsp_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=132,
)


_RTSPFEEDHEALTHCHECK = _descriptor.Descriptor(
  name='RTSPFeedHealthCheck',
  full_name='VODService.RTSPFeedHealthCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_flag', full_name='VODService.RTSPFeedHealthCheck.status_flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='VODService.RTSPFeedHealthCheck.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=200,
)


_HEALTHCHECKRESULT = _descriptor.Descriptor(
  name='HealthCheckResult',
  full_name='VODService.HealthCheckResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='VODService.HealthCheckResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='VODService.HealthCheckResult.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feeds', full_name='VODService.HealthCheckResult.feeds', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=310,
)


_VODSTARTMESSAGE = _descriptor.Descriptor(
  name='VODStartMessage',
  full_name='VODService.VODStartMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='VODService.VODStartMessage.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rtsp_url', full_name='VODService.VODStartMessage.rtsp_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=368,
)


_VODSTOPMESSAGE = _descriptor.Descriptor(
  name='VODStopMessage',
  full_name='VODService.VODStopMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtsp_url', full_name='VODService.VODStopMessage.rtsp_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=404,
)


_VODSTARTRESPONSE = _descriptor.Descriptor(
  name='VODStartResponse',
  full_name='VODService.VODStartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='VODService.VODStartResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='VODService.VODStartResponse.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=465,
)


_VODSTATUSMESSAGE = _descriptor.Descriptor(
  name='VODStatusMessage',
  full_name='VODService.VODStatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='VODService.VODStatusMessage.stream_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=506,
)


_VODSTATUSRESPONSE = _descriptor.Descriptor(
  name='VODStatusResponse',
  full_name='VODService.VODStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='VODService.VODStatusResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='VODService.VODStatusResponse.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_running', full_name='VODService.VODStatusResponse.stream_running', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_log', full_name='VODService.VODStatusResponse.stream_log', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=612,
)


_VODSTOPRESPONSE = _descriptor.Descriptor(
  name='VODStopResponse',
  full_name='VODService.VODStopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='VODService.VODStopResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='VODService.VODStopResponse.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=672,
)

_HEALTHCHECKMESSAGE.fields_by_name['rtsp_urls'].message_type = _RTSPURLMESSAGE
_HEALTHCHECKRESULT.fields_by_name['feeds'].message_type = _RTSPFEEDHEALTHCHECK
DESCRIPTOR.message_types_by_name['HealthCheckMessage'] = _HEALTHCHECKMESSAGE
DESCRIPTOR.message_types_by_name['RtspUrlMessage'] = _RTSPURLMESSAGE
DESCRIPTOR.message_types_by_name['RTSPFeedHealthCheck'] = _RTSPFEEDHEALTHCHECK
DESCRIPTOR.message_types_by_name['HealthCheckResult'] = _HEALTHCHECKRESULT
DESCRIPTOR.message_types_by_name['VODStartMessage'] = _VODSTARTMESSAGE
DESCRIPTOR.message_types_by_name['VODStopMessage'] = _VODSTOPMESSAGE
DESCRIPTOR.message_types_by_name['VODStartResponse'] = _VODSTARTRESPONSE
DESCRIPTOR.message_types_by_name['VODStatusMessage'] = _VODSTATUSMESSAGE
DESCRIPTOR.message_types_by_name['VODStatusResponse'] = _VODSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['VODStopResponse'] = _VODSTOPRESPONSE
DESCRIPTOR.enum_types_by_name['DType'] = _DTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthCheckMessage = _reflection.GeneratedProtocolMessageType('HealthCheckMessage', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKMESSAGE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.HealthCheckMessage)
  })
_sym_db.RegisterMessage(HealthCheckMessage)

RtspUrlMessage = _reflection.GeneratedProtocolMessageType('RtspUrlMessage', (_message.Message,), {
  'DESCRIPTOR' : _RTSPURLMESSAGE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.RtspUrlMessage)
  })
_sym_db.RegisterMessage(RtspUrlMessage)

RTSPFeedHealthCheck = _reflection.GeneratedProtocolMessageType('RTSPFeedHealthCheck', (_message.Message,), {
  'DESCRIPTOR' : _RTSPFEEDHEALTHCHECK,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.RTSPFeedHealthCheck)
  })
_sym_db.RegisterMessage(RTSPFeedHealthCheck)

HealthCheckResult = _reflection.GeneratedProtocolMessageType('HealthCheckResult', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESULT,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.HealthCheckResult)
  })
_sym_db.RegisterMessage(HealthCheckResult)

VODStartMessage = _reflection.GeneratedProtocolMessageType('VODStartMessage', (_message.Message,), {
  'DESCRIPTOR' : _VODSTARTMESSAGE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.VODStartMessage)
  })
_sym_db.RegisterMessage(VODStartMessage)

VODStopMessage = _reflection.GeneratedProtocolMessageType('VODStopMessage', (_message.Message,), {
  'DESCRIPTOR' : _VODSTOPMESSAGE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.VODStopMessage)
  })
_sym_db.RegisterMessage(VODStopMessage)

VODStartResponse = _reflection.GeneratedProtocolMessageType('VODStartResponse', (_message.Message,), {
  'DESCRIPTOR' : _VODSTARTRESPONSE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.VODStartResponse)
  })
_sym_db.RegisterMessage(VODStartResponse)

VODStatusMessage = _reflection.GeneratedProtocolMessageType('VODStatusMessage', (_message.Message,), {
  'DESCRIPTOR' : _VODSTATUSMESSAGE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.VODStatusMessage)
  })
_sym_db.RegisterMessage(VODStatusMessage)

VODStatusResponse = _reflection.GeneratedProtocolMessageType('VODStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _VODSTATUSRESPONSE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.VODStatusResponse)
  })
_sym_db.RegisterMessage(VODStatusResponse)

VODStopResponse = _reflection.GeneratedProtocolMessageType('VODStopResponse', (_message.Message,), {
  'DESCRIPTOR' : _VODSTOPRESPONSE,
  '__module__' : 'vod_api_pb2'
  # @@protoc_insertion_point(class_scope:VODService.VODStopResponse)
  })
_sym_db.RegisterMessage(VODStopResponse)



_VODSERVICE = _descriptor.ServiceDescriptor(
  name='VODService',
  full_name='VODService.VODService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=733,
  serialized_end=1049,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartVOD',
    full_name='VODService.VODService.StartVOD',
    index=0,
    containing_service=None,
    input_type=_VODSTARTMESSAGE,
    output_type=_VODSTARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopVOD',
    full_name='VODService.VODService.StopVOD',
    index=1,
    containing_service=None,
    input_type=_VODSTOPMESSAGE,
    output_type=_VODSTOPRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckVODStatus',
    full_name='VODService.VODService.CheckVODStatus',
    index=2,
    containing_service=None,
    input_type=_VODSTATUSMESSAGE,
    output_type=_VODSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='VODService.VODService.HealthCheck',
    index=3,
    containing_service=None,
    input_type=_HEALTHCHECKMESSAGE,
    output_type=_HEALTHCHECKRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VODSERVICE)

DESCRIPTOR.services_by_name['VODService'] = _VODSERVICE

# @@protoc_insertion_point(module_scope)
