# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference_api.proto',
  package='InferenceService',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13inference_api.proto\x12\x10InferenceService\x1a\x1bgoogle/protobuf/empty.proto\"A\n\x16StartInferenceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\"\x14\n\x12StatusCheckRequest\"=\n\x13StatusCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2\xe2\x02\n\x10InferenceService\x12\\\n\x0bStatusCheck\x12$.InferenceService.StatusCheckRequest\x1a%.InferenceService.StatusCheckResponse\"\x00\x12T\n\x0eStartInference\x12\x16.google.protobuf.Empty\x1a(.InferenceService.StartInferenceResponse\"\x00\x12S\n\rStopInference\x12\x16.google.protobuf.Empty\x1a(.InferenceService.StartInferenceResponse\"\x00\x12\x45\n\x11\x43onfigUpdateAlert\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STARTINFERENCERESPONSE = _descriptor.Descriptor(
  name='StartInferenceResponse',
  full_name='InferenceService.StartInferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='InferenceService.StartInferenceResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='InferenceService.StartInferenceResponse.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=135,
)


_STATUSCHECKREQUEST = _descriptor.Descriptor(
  name='StatusCheckRequest',
  full_name='InferenceService.StatusCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=157,
)


_STATUSCHECKRESPONSE = _descriptor.Descriptor(
  name='StatusCheckResponse',
  full_name='InferenceService.StatusCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='InferenceService.StatusCheckResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='InferenceService.StatusCheckResponse.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['StartInferenceResponse'] = _STARTINFERENCERESPONSE
DESCRIPTOR.message_types_by_name['StatusCheckRequest'] = _STATUSCHECKREQUEST
DESCRIPTOR.message_types_by_name['StatusCheckResponse'] = _STATUSCHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartInferenceResponse = _reflection.GeneratedProtocolMessageType('StartInferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTINFERENCERESPONSE,
  '__module__' : 'inference_api_pb2'
  # @@protoc_insertion_point(class_scope:InferenceService.StartInferenceResponse)
  })
_sym_db.RegisterMessage(StartInferenceResponse)

StatusCheckRequest = _reflection.GeneratedProtocolMessageType('StatusCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSCHECKREQUEST,
  '__module__' : 'inference_api_pb2'
  # @@protoc_insertion_point(class_scope:InferenceService.StatusCheckRequest)
  })
_sym_db.RegisterMessage(StatusCheckRequest)

StatusCheckResponse = _reflection.GeneratedProtocolMessageType('StatusCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSCHECKRESPONSE,
  '__module__' : 'inference_api_pb2'
  # @@protoc_insertion_point(class_scope:InferenceService.StatusCheckResponse)
  })
_sym_db.RegisterMessage(StatusCheckResponse)



_INFERENCESERVICE = _descriptor.ServiceDescriptor(
  name='InferenceService',
  full_name='InferenceService.InferenceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=223,
  serialized_end=577,
  methods=[
  _descriptor.MethodDescriptor(
    name='StatusCheck',
    full_name='InferenceService.InferenceService.StatusCheck',
    index=0,
    containing_service=None,
    input_type=_STATUSCHECKREQUEST,
    output_type=_STATUSCHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartInference',
    full_name='InferenceService.InferenceService.StartInference',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_STARTINFERENCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopInference',
    full_name='InferenceService.InferenceService.StopInference',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_STARTINFERENCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigUpdateAlert',
    full_name='InferenceService.InferenceService.ConfigUpdateAlert',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFERENCESERVICE)

DESCRIPTOR.services_by_name['InferenceService'] = _INFERENCESERVICE

# @@protoc_insertion_point(module_scope)
